dist: trusty
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
env:
  - COMPOSER_REQUIRE=""
  - COMPOSER_REQUIRE="composer require masterminds/html5"
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
install:
  - $COMPOSER_REQUIRE
before_script: composer install
